In [8]:
import numpy as np
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)
list_
array_list

array([1, 2, 3, 4, 5])

1.

A list is a built-in data structure that can store a collection of items. It can hold elements of different types and can dynamically change size, whereas array list refers to arrays provided by libraries like numpy or array from the array module.

In [6]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


2.

In [9]:
import numpy as np
list_ = [1, 2.5, 'three', True]
array_list = np.array([1, 2.5, 'three', True])
print("Data types of elements in list_:")
for element in list_:
    print(f'Element: {element}, Data type: {type(element)}')
print("\nData types of elements in array_list:")
for element in array_list:
    print(f'Element: {element}, Data type: {type(element)}')


Data types of elements in list_:
Element: 1, Data type: <class 'int'>
Element: 2.5, Data type: <class 'float'>
Element: three, Data type: <class 'str'>
Element: True, Data type: <class 'bool'>

Data types of elements in array_list:
Element: 1, Data type: <class 'numpy.str_'>
Element: 2.5, Data type: <class 'numpy.str_'>
Element: three, Data type: <class 'numpy.str_'>
Element: True, Data type: <class 'numpy.str_'>


3.

In [11]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list_str = np.array(list_)
array_list_int = np.array(list_, dtype=int)
print("Data types of elements in list_:")
for element in list_:
    print(f'Element: {element}, Data type: {type(element)}')
print("\nData types of elements in array_list (string type):")
for element in array_list_str:
    print(f'Element: {element}, Data type: {type(element)}')
print("\nData types of elements in array_list (integer type):")
for element in array_list_int:
    print(f'Element: {element}, Data type: {type(element)}')

Data types of elements in list_:
Element: 1, Data type: <class 'str'>
Element: 2, Data type: <class 'str'>
Element: 3, Data type: <class 'str'>
Element: 4, Data type: <class 'str'>
Element: 5, Data type: <class 'str'>

Data types of elements in array_list (string type):
Element: 1, Data type: <class 'numpy.str_'>
Element: 2, Data type: <class 'numpy.str_'>
Element: 3, Data type: <class 'numpy.str_'>
Element: 4, Data type: <class 'numpy.str_'>
Element: 5, Data type: <class 'numpy.str_'>

Data types of elements in array_list (integer type):
Element: 1, Data type: <class 'numpy.int64'>
Element: 2, Data type: <class 'numpy.int64'>
Element: 3, Data type: <class 'numpy.int64'>
Element: 4, Data type: <class 'numpy.int64'>
Element: 5, Data type: <class 'numpy.int64'>


4.

In [14]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)
print(num_array)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


[[1 2 3]
 [4 5 6]]
Shape of num_array: (2, 3)
Size of num_array: 6


5.

In [17]:
np.zeros((3,3))        #Creating the zero matrix of 3*3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

6.

In [ ]:
np.eye